UPDATE rosters set player = 'O.J. Howard' where player = 'O.J. How';
UPDATE rosters set player = 'Baker Mayfield' where player = 'Baker May';
UPDATE rosters set player = '(Empty)' where player = '';
UPDATE rosters set team = 'JAX' where player = 'Laviska Shenault Jr.';
UPDATE rosters set team = 'CIN' where player = 'A.J. Green' and year = 2019;
UPDATE rosters set team = 'LAR' where player = 'Aaron Donald';
UPDATE rosters set team = 'GB' where player = 'A.J. Hawk';
UPDATE rosters set team = 'GB' where player = 'Aaron Kampman';
UPDATE rosters set team = 'CHI' where player = 'Allen Robinson II' and year > 2017 and year < 2022;
UPDATE rosters set team = 'CHI' where player = 'Allen Robinson II' and year < 2018;
UPDATE rosters set team = 'LAR' where player = 'Allen Robinson II' and year = 2022;
UPDATE rosters set team = 'PIT' where player = 'Allen Robinson II' and year = 2023;
UPDATE rosters set team = 'STL', position = 'RB' where player = 'Benny Cunningham Jr.' and year < 2016;
UPDATE rosters set team = 'PIT' where player = 'Benny Snell Jr.';
UPDATE rosters set team = 'TB' where player = 'Cadillac Williams' and year < 2011;
UPDATE rosters set team = 'STL' where player = 'Cadillac Williams' and year = 2011;
UPDATE rosters set team = 'DET' where player = 'DJ Chark Jr.' and year = 2022;
UPDATE rosters set team = 'JAX' where player = 'DJ Chark Jr.' and year < 2022;
UPDATE rosters set team = 'CAR' where player = 'DJ Moore' and year < 2023;
UPDATE rosters set team = 'CHI' where player = 'DJ Moore' and year = 2023;
UPDATE rosters set team = 'SEA' where player = 'DK Metcalf';
UPDATE rosters set team = 'LAR' where player = 'Darrell Henderson Jr.';
UPDATE rosters set team = 'NO' where player = 'Deonte Harris';
UPDATE rosters set team = 'BUF' where player = 'Gabe Davis';
UPDATE rosters set team = 'JAX' where player = 'Gardner Minshew II' and year = 2020;
UPDATE rosters set team = 'PHI' where player = 'Gardner Minshew II' and year = 2021;
UPDATE rosters set team = 'LV' where player = 'Henry Ruggs III';
UPDATE rosters set team = 'SF' where player = 'Jeff Wilson Jr.' and year < 2022;
UPDATE rosters set team = 'SF' where player = 'Jeff Wilson Jr.' and year = 2022 and week < 9;
UPDATE rosters set team = 'MIA' where player = 'Jeff Wilson Jr.' and year = 2022 and week > 9;
UPDATE rosters set team = 'MIA' where player = 'Jeff Wilson Jr.' and year = 2023;
UPDATE rosters set team = 'CLE' where player = 'Josh Cribbs' and year < 2013;
UPDATE rosters set team = 'LAC' where player = 'Joshua Palmer';